# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_commander_dt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import socket
from PyQt5 import QtCore, QtGui, QtWidgets
import binascii
#import mod_datpar as datpar
import datetime
from PyQt5.QtWidgets import QApplication
socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

recv_time = 60

# main class

# UI (button)
# pushButton : Connect to
# psuhButton_2 : Disconnect
# pushButton_3 : Write to
# pushButton_4 : New
# pushButton_5 : Execute
# pushButton_6 : Start
# pushButton_8 : Clear

# UI (lineEdit)
# lineEdit : IP
# lineEdit_2 : port
# lineEdit_3 : nbyte
# lineEdit_4 : save_filename
# lineEdit_13 : interval second

# UI (listView)
# listView : byte per sec / disconnect

# UI (timeEdit)
# timeEdit : parsing start time
# timeEdit_2 : parsing stop time
# timeEdit_3 : poll interval time

# UI (check box)
# checkBox : poll interval second apply

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1480, 919))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 8, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 3, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 8, 1, 2)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 10, 1, 1)
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 8)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 8, 1, 2)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout.addWidget(self.timeEdit_2, 2, 10, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 8, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 9, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 11, 1, 1)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout.addWidget(self.timeEdit_3, 4, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 4, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 6, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 4, 8, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 11, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 5, 0, 1, 12)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 버튼 클릭
        self.pushButton.clicked.connect(self.button_event_conn)
        self.pushButton_2.clicked.connect(self.button_event_write)
        self.pushButton_3.clicked.connect(self.button_event_new)
        self.pushButton_5.clicked.connect(self.button_event_save_start())
        self.pushButton_6.clicked.connect(self.button_event_save_stop())
        
        # 변수 추가
        self.IP = ""
        self.port = ""
        self.nbyte =""
        self.filename =""
        self.hex_data = ""
        
        # save 
        self.start_time =""
        self.start_dd = ""
        self.start_hh = ""
        self.start_mm = ""
        self.start_ss = ""
        
        self.stop_time =""
        self.stop_dd = ""
        self.stop_hh = ""
        self.stop_mm = ""
        self.stop_ss = ""
        

    # 서버 연결 (connect to)
    def button_event_conn(self):
        self.IP = self.lineEdit.text()
        self.port = int(self.lineEdit_2.text())
        self.nbyte = self.lineEdit_3.text()
        socket.connect((self.IP, self.port))
        start = datetime.perf_counter()
        while True:
            QApplication.processEvents()
            data = socket.recv(4096)
            # self.hex_data = binascii.hexlify(data).decode('utf-8')
            end = datetime.perf_counter()
            print('hex_data :', len(data))
            count = end-start
            print(round(count,4))
            if count >= recv_time:
                socket.close()
                break
    
    # save file name (write to)
    def button_event_write(self):
        self.filename = self.lineEdit_4.text()
        
    def button_event_new(self):
        self.lineEdit_4.clear()
        
    # 데이터 저장
# =============================================================================
#     def save_file(self):
#         with open(self.filename,'w') as f:
#             while True:
#                 f.write(self.hex_data)    
# =============================================================================
    
    # save start
    def button_event_save_start(self):
        self.start_time = self.timeEdit.time()
        self.start_dd = self.start_time.days()
        self.start_hh = self.start_time.hours()
        self.start_mm = self.start_time.minutes()
        self.start_ss = self.start_time.seconds()
        
        self.stop_time = self.timeEdit.time()
        self.stop_dd = self.stop.time.day()
        self.stop_hh = self.stop.time.hour()
        self.stop_mm = self.stop.time.minute()
        self.stop_ss = self.stop.time.second()
        
        with open(self.filename,'w') as f:
            while True:
                current_time =QtCore.QTime.currentTime()
                if current_time >= self.start_time and current_time <= self.stop_time:
                    self.IP
                
                else:
                    self.clear()
    
    def button_event_save_stop(self):
        stop =0
    
    # 완전 클리어
    def clear(self):
        clear = 0
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Connect setup</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Time parsing setup</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Connect to"))
        self.pushButton_2.setText(_translate("MainWindow", "Disconnect"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Start time(dd.hh.mm.ss) : </span></p></body></html>"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "dd.hh.mm.ss"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">End time(dd.hh.mm.ss) :</span></p></body></html>"))
        self.timeEdit_2.setDisplayFormat(_translate("MainWindow", "dd.hh.mm.ss"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Poll Interval setup</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Write to"))
        self.pushButton_4.setText(_translate("MainWindow", "New"))
        self.timeEdit_3.setDisplayFormat(_translate("MainWindow", "hh.mm.ss"))
        self.checkBox.setText(_translate("MainWindow", "Poll Interval :"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Seconds</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Execute"))
        self.pushButton_6.setText(_translate("MainWindow", "Start"))
        self.pushButton_8.setText(_translate("MainWindow", "Clear"))

# main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
