# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_commander_dt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import socket
from PyQt5 import QtCore, QtGui, QtWidgets
import binascii
#import mod_datpar as datpar
import datetime
from PyQt5.QtWidgets import QApplication
socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

recv_time = 60

# main class\

# UI (button)
# pushButton : Connect to
# psuhButton_2 : Write to
# pushButton_3 : New
# pushButton_4 : Execute
# pushButton_5 : Start
# pushButton_6 : Stop
# pushButton_7 : Clear
# pushButton_8 : Done

# UI (lineEdit)
# lineEdit : IP
# lineEdit_2 : port
# lineEdit_3 : nbyte
# lineEdit_4 : save_filename
# lineEdit_5 : interval second

# UI (listView)
# listView : byte per sec / disconnect
# listView_2 : plot report

# UI (timeEdit)
# timeEdit : save start time
# timeEdit_2 : save stop time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 923)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 50, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 80, 61, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 10, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 10, 71, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 10, 41, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 50, 301, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 90, 441, 31))
        self.listView.setObjectName("listView")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 100, 61, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 140, 1131, 741))
        self.graphicsView.setObjectName("graphicsView")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(480, 30, 321, 41))
        self.listView_2.setObjectName("listView_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 50, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 90, 71, 21))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(550, 90, 21, 21))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 90, 91, 21))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 100, 61, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 40, 181, 21))
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(820, 70, 181, 21))
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(960, 100, 61, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1090, 100, 61, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 10, 131, 21))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(480, 10, 141, 21))
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(660, 80, 41, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(1000, 40, 118, 20))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(1000, 70, 118, 20))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.listView.raise_()
        self.pushButton_5.raise_()
        self.graphicsView.raise_()
        self.listView_2.raise_()
        self.pushButton_3.raise_()
        self.label_2.raise_()
        self.checkBox.raise_()
        self.label_3.raise_()
        self.pushButton_6.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit_13.raise_()
        self.timeEdit.raise_()
        self.timeEdit_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # 버튼 클릭
        self.pushButton.clicked.connect(self.button_event_conn)
        self.pushButton_2.clicked.connect(self.button_event_write)
        self.pushButton_3.clicked.connect(self.button_event_new)
        self.pushButton_5.clicked.connect(self.button_event_save_start())
        self.pushButton_6.clicked.connect(self.button_event_save_stop())
        
        # 변수 추가
        self.IP = ""
        self.port = ""
        self.nbyte =""
        self.filename =""
        self.hex_data = ""
        
        # save 
        self.start_time =""
        self.start_dd = ""
        self.start_hh = ""
        self.start_mm = ""
        self.start_ss = ""
        
        self.stop_time =""
        self.stop_dd = ""
        self.stop_hh = ""
        self.stop_mm = ""
        self.stop_ss = ""
        

    # 서버 연결 (connect to)
    def button_event_conn(self):
        self.IP = self.lineEdit.text()
        self.port = int(self.lineEdit_2.text())
        self.nbyte = self.lineEdit_3.text()
        socket.connect((self.IP, self.port))
        start = datetime.perf_counter()
        while True:
            QApplication.processEvents()
            data = socket.recv(4096)
            # self.hex_data = binascii.hexlify(data).decode('utf-8')
            end = datetime.perf_counter()
            print('hex_data :', len(data))
            count = end-start
            print(round(count,4))
            if count >= recv_time:
                socket.close()
                break
    
    # save file name (write to)
    def button_event_write(self):
        self.filename = self.lineEdit_4.text()
        
    def button_event_new(self):
        self.lineEdit_4.clear()
        
    # 데이터 저장
# =============================================================================
#     def save_file(self):
#         with open(self.filename,'w') as f:
#             while True:
#                 f.write(self.hex_data)    
# =============================================================================
    
    # save start
    def button_event_save_start(self):
        self.start_time = self.timeEdit.time()
        self.start_dd = self.start_time.days()
        self.start_hh = self.start_time.hours()
        self.start_mm = self.start_time.minutes()
        self.start_ss = self.start_time.seconds()
        
        self.stop_time = self.timeEdit.time()
        self.stop_dd = self.stop.time.day()
        self.stop_hh = self.stop.time.hour()
        self.stop_mm = self.stop.time.minute()
        self.stop_ss = self.stop.time.second()
        
        with open(self.filename,'w') as f:
            while True:
                current_time =QtCore.QTime.currentTime()
                if current_time >= self.start_time and current_time <= self.stop_time:
                    self.IP
                
                else:
                    self.clear()
    
    def button_event_save_stop(self):
        stop =0
        
        
    
    # 완전 클리어
    def clear(self):
        clear = 0
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Connect to"))
        self.pushButton_2.setText(_translate("MainWindow", "Write to"))
        self.pushButton_4.setText(_translate("MainWindow", "Execute"))
        self.pushButton_5.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "New"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Seconds</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Poll interval : </span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Stop"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Start time(dd.hh.mm.ss) : </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Stop time(dd.hh.mm.ss) :</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Clear"))
        self.pushButton_8.setText(_translate("MainWindow", "Done"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Save time setup</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Poll Interval setup</span></p></body></html>"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "dd.hh.mm.ss"))
        self.timeEdit_2.setDisplayFormat(_translate("MainWindow", "dd.hh.mm.ss"))

# main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
