# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connect_state.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

# UI

# UI (button)
# connect : Connect to
# write : write to
# New : New
# Done : Done

# UI (lineEdit)
# IP : IP
# port : port
# save_filepath : save_filepath

# UI (label)
# connect_state : connect_state

# UI (timeEdit)
# Start_time : Start_time
# End_time : End_time




Logo_filename_path = r'SSIL_logo.PNG'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LUSEM_DATA")
        MainWindow.resize(810, 610)
        MainWindow.setWindowIcon(QIcon(Logo_filename_path))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IP = QtWidgets.QLineEdit(self.centralwidget)
        self.IP.setGeometry(QtCore.QRect(130, 30, 91, 20))
        self.IP.setObjectName("IP")
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(230, 30, 41, 20))
        self.port.setObjectName("port")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.connect.setObjectName("connect")
        self.connect_state = QtWidgets.QLabel(self.centralwidget)
        self.connect_state.setGeometry(QtCore.QRect(20, 70, 341, 16))
        self.connect_state.setObjectName("connect_state")
        self.Start_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.Start_time.setGeometry(QtCore.QRect(20, 110, 91, 22))
        self.Start_time.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.Start_time.setObjectName("Start_time")
        self.End_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.End_time.setGeometry(QtCore.QRect(20, 140, 91, 22))
        self.End_time.setCurrentSection(QtWidgets.QDateTimeEdit.NoSection)
        self.End_time.setObjectName("End_time")
        self.write = QtWidgets.QPushButton(self.centralwidget)
        self.write.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.write.setObjectName("write")
        self.save_filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.save_filepath.setGeometry(QtCore.QRect(110, 170, 281, 20))
        self.save_filepath.setObjectName("save_filepath")
        self.New = QtWidgets.QPushButton(self.centralwidget)
        self.New.setGeometry(QtCore.QRect(400, 170, 75, 23))
        self.New.setObjectName("New")
        self.Done = QtWidgets.QPushButton(self.centralwidget)
        self.Done.setGeometry(QtCore.QRect(490, 170, 75, 23))
        self.Done.setObjectName("Done")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("LUSEM_DATA", "LUSEM_DATA"))
        self.IP.setText(_translate("LUSEM_DATA", "192.168.1.120"))
        self.port.setText(_translate("LUSEM_DATA", "4040"))
        self.connect.setText(_translate("LUSEM_DATA", "Connect to"))
        self.connect_state.setText(_translate("LUSEM_DATA", "\"Connect state\""))
        self.Start_time.setDisplayFormat(_translate("LUSEM_DATA", "dd.hh.mm.ss"))
        self.End_time.setDisplayFormat(_translate("LUSEM_DATA", "dd.hh.mm.ss"))
        self.write.setText(_translate("LUSEM_DATA", "Write to"))
        self.save_filepath.setText(_translate("LUSEM_DATA", "\"Default save filepath\""))
        self.New.setText(_translate("LUSEM_DATA", "New"))
        self.Done.setText(_translate("LUSEM_DATA", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
